# Generated by Django 4.0.3 on 2022-03-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stuff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("json_current", models.JSONField()),
                ("json_new", models.JSONField()),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
